Feature/add sonarqube (#5)
Several fixes

diff --git a/runme b/runme
--- a/runme
+++ b/runme
@@ -2,13 +2,7 @@
 
 SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
 
-# Los códigos de color se eliminan ya que el uso de "\e" y "-e" en echo no es compatible con POSIX
-BLUE=""
-GREEN=""
-RESET=""
-TIMEOUT="25s"
-
-# En POSIX no existen arreglos asociativos, utilizaremos variables individuales
+# En POSIX no existen arrays asociativos, utilizaremos variables individuales
 OPTION_FLAGS_docs=false
 OPTION_FLAGS_loop=false
 OPTION_FLAGS_leak=false
@@ -16,15 +10,17 @@ OPTION_FLAGS_coverage=false
 OPTION_FLAGS_debug=false
 OPTION_FLAGS_clean=false
 OPTION_FLAGS_compile_commands=false
+OPTION_FLAGS_thread=false
 
 # Lista de targets de make
 MAKE_TARGETS_docs="doxygen-doc"
 MAKE_TARGETS_leak="leak-check"
 MAKE_TARGETS_coverage="coverage"
-MAKE_TARGETS_debug="valgrind"
+MAKE_TARGETS_debug="check"
+MAKE_TARGETS_thread="thread-check"
 
 # Lista de opciones para iterar
-MAKE_TARGETS_list="docs leak coverage debug"
+MAKE_TARGETS_list="docs leak coverage debug thread"
 
 banner() {
   title="$1"
@@ -50,7 +46,7 @@ configure() {
   autoreconf --install
 
   mkdir -p "${SCRIPT_DIR}/build"
-  cd "${SCRIPT_DIR}/build"
+  cd "${SCRIPT_DIR}/build" || exit
   "${SCRIPT_DIR}/configure" ${params} &&
     wait_key
 }
@@ -60,6 +56,13 @@ make_exec() {
   banner "MAKE ${params}"
 
   make ${params} &&
+    wait_key
+}
+
+make_tests() {
+  banner "MAKE check"
+
+  make check &&
     wait_key
 }
 
@@ -75,9 +78,10 @@ show_help() {
   echo "Usage: $0 [options]"
   echo "Options:"
   echo "  -d, --docs                 Enable document generation"
-  echo "  -l, --leak                 Enable memory leak check (mutually exclusive with --coverage and --debug)"
-  echo "  -c, --coverage             Enable coverage tests (mutually exclusive with --leak and --debug)"
-  echo "  -g, --debug                Enable debug mode and run valgrind (mutually exclusive with --leak and --coverage)"
+  echo "  -l, --leak                 Enable memory leak check (mutually exclusive with --coverage, --debug, and --thread)"
+  echo "  -c, --coverage             Enable coverage tests (mutually exclusive with --leak, --debug, and --thread)"
+  echo "  -g, --debug                Enable debug mode and run valgrind (mutually exclusive with --leak, --coverage, and --thread)"
+  echo "  -t, --thread               Enable thread-sanitize mode (mutually exclusive with --leak, --coverage, and --debug)"
   echo "  -i, --loop                 Enable loop mode"
   echo "  -n, --clean                Clean build directory before building and do not clean after"
   echo "  -m, --compile-commands     Execute compile_commands target"
@@ -107,7 +111,7 @@ loop_execution() {
     fi
     executed=1
     make_exec || continue
-    make_exec check || {
+    make_tests || {
       echo "Running tests individually..."
       # Ejecutar los tests individualmente si falla make check
       for test_file in "${SCRIPT_DIR}/build/tests/"*_test; do
@@ -142,7 +146,7 @@ while [ $# -gt 0 ]; do
     ;;
   -l | --leak)
     if [ -n "$selected_mode" ]; then
-      echo "Error: Options --leak, --coverage, and --debug are mutually exclusive."
+      echo "Error: Options --leak, --coverage, --debug, and --thread are mutually exclusive."
       exit 1
     fi
     OPTION_FLAGS_leak=true
@@ -151,7 +155,7 @@ while [ $# -gt 0 ]; do
     ;;
   -c | --coverage)
     if [ -n "$selected_mode" ]; then
-      echo "Error: Options --leak, --coverage, and --debug are mutually exclusive."
+      echo "Error: Options --leak, --coverage, --debug, and --thread are mutually exclusive."
       exit 1
     fi
     OPTION_FLAGS_coverage=true
@@ -160,11 +164,20 @@ while [ $# -gt 0 ]; do
     ;;
   -g | --debug)
     if [ -n "$selected_mode" ]; then
-      echo "Error: Options --leak, --coverage, and --debug are mutually exclusive."
+      echo "Error: Options --leak, --coverage, --debug, and --thread are mutually exclusive."
       exit 1
     fi
     OPTION_FLAGS_debug=true
     selected_mode="debug"
+    shift
+    ;;
+  -t | --thread)
+    if [ -n "$selected_mode" ]; then
+      echo "Error: Options --leak, --coverage, --debug, and --thread are mutually exclusive."
+      exit 1
+    fi
+    OPTION_FLAGS_thread=true
+    selected_mode="thread"
     shift
     ;;
   -i | --loop)
@@ -175,8 +188,8 @@ while [ $# -gt 0 ]; do
     OPTION_FLAGS_clean=true
     shift
     ;;
-  -m | --nocompile-commands)
-    OPTION_FLAGS_compile_commands=false
+  -m | --compile-commands)
+    OPTION_FLAGS_compile_commands=true
     shift
     ;;
   -h | --help)
@@ -215,6 +228,10 @@ if [ "${OPTION_FLAGS_debug}" = true ]; then
   BUILD_MODES="${BUILD_MODES} debug"
 fi
 
+if [ "${OPTION_FLAGS_thread}" = true ]; then
+  BUILD_MODES="${BUILD_MODES} thread-sanitize"
+fi
+
 if [ -n "${BUILD_MODES}" ]; then
   # Eliminar espacios iniciales
   BUILD_MODES="$(echo "${BUILD_MODES}" | sed 's/^ *//')"
@@ -241,7 +258,7 @@ else
     make_exec compile_commands
   fi
   make_exec
-  make_exec check || ./tests/saurion_test
+  make_tests || ./tests/saurion_test
   for option in $MAKE_TARGETS_list; do
     option_flag_var="OPTION_FLAGS_${option}"
     option_flag_value=$(eval echo \$$option_flag_var)
